repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        args:
          - -c
          - .yamllint.yml

  - repo: https://github.com/ansible/ansible-lint
    rev: v25.9.2
    hooks:
      - id: ansible-lint
        additional_dependencies:
          - ansible
        files: ^config/ansible/

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.98.3
    hooks:
      - id: terraform_fmt
        files: ^infra/terraform/
